create database AgenciadeTours
use AgenciadeTours

CREATE TABLE Paises (
PaisID INT IDENTITY(1,1) PRIMARY KEY,
Nombre NVARCHAR(100) NOT NULL
)

CREATE TABLE Destinos (
DestinoID INT IDENTITY(1,1) PRIMARY KEY,
Nombre NVARCHAR(150) NOT NULL,
PaisID INT NOT NULL,
Dias_Duracion INT NOT NULL CHECK (Dias_Duracion BETWEEN 0 AND 365),
Horas_Duracion INT NOT NULL CHECK (Horas_Duracion BETWEEN 0 AND 23),

CONSTRAINT FK_Destinos_Paises
FOREIGN KEY (PaisID) REFERENCES Paises(PaisID)
ON DELETE CASCADE
)

CREATE TABLE Tours (
TourID INT IDENTITY(1,1) PRIMARY KEY,
Nombre NVARCHAR(200) NOT NULL,
PaisID INT NOT NULL,
DestinoID INT NOT NULL,
Fecha DATE NOT NULL,
Hora TIME NOT NULL,
Precio DECIMAL(18,2) NOT NULL CHECK (Precio >= 0),

CONSTRAINT FK_Tours_Paises
FOREIGN KEY (PaisID) REFERENCES Paises(PaisID),

CONSTRAINT FK_Tours_Destinos
FOREIGN KEY (DestinoID) REFERENCES Destinos(DestinoID)
)

